name: viva
channels:
      - defaults
      - conda-forge
dependencies:
      - python=3.12
      - pip
      - nltk
      - pip:
              - fastapi
              - uvicorn
              - python-multipart
              - python-dotenv
              - sqlalchemy
              - psycopg2-binary
              - anthropic
              - langchain
              - openai
              - pydantic
              - aiohttp
              - aliyun-python-sdk-core
              - aliyun-python-sdk-kms
              - assemblyai
              - beautifulsoup4
              - flask
              - jieba
              - langchain-anthropic
              - langchain-openai
              - matplotlib
              - mysqlclient
              - numpy
              - pandas
              - python-telegram-bot
              - spacy
              - tiktoken
              - oss2
